project_name = "svcmgmtops"
project      = "svcmgmtops"
envname      = "sandbox"
region       = "europe-west1"
gcp_project_id = "svcmgmtops-sandbox"
resource_prefix = "svcmgmtops-sandbox"
state_bucket = "svcmgmtops-sandbox-bucket-tf-state"
