trigger:
- main
pool:
  vmImage: 'ubuntu-latest' # Uses Microsoft's free hosted servers
steps:
- task: AzureCLI@3
  inputs:
    connectionType: 'azureRM'
    azureSubscription: 'sc-ado-gcp-aicoe'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo $idToken > $(Pipeline.Workspace)/.workload_identity.jwt
       
      mkdir -p $(Build.ArtifactStagingDirectory)/wif-debug
      
      cp $(Pipeline.Workspace)/.workload_identity.jwt $(Build.ArtifactStagingDirectory)/wif-debug
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'wif-debug'
    publishLocation: 'Container'
  