project_name             = "ai-cmo-dev"
project                  = "ai-cmo-dev"
envname                  = "dev"
region                   = "europe-west1"
cloud_run_service_name2  = "sales-research-application"
