trigger:
  branches:
    include:
      - main
      - sandbox-v1
  paths:
    include:
      - terraform/projects/aicoeaiworkshop/**
      - terraform/modules/**

pool:
  vmImage: ubuntu-latest

extends:
  template: pipeline-template.yml
  parameters:
    projectName: aicoeaiworkshop
    tfEnv: sandox
    tfProject: aicoeaiworkshop
    gcpProjectId: aicoeaiworkshopsandox
    gcpProjectNumber: '775524029915'
    wifServiceAccount: aicoe-sbx-wif-sa-tf@aicoesandox.iam.gserviceaccount.com
    enableStatic: true
    enableNetwork: false
    enableInfra: false
