trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - terraform/projects/vegadev/**
      - terraform/modules/**

pool:
  vmImage: ubuntu-latest

extends:
  template: pipeline-template.yml
  parameters:
    projectName: vegadev
    tfEnv: dev
    tfProject: vegadev-499613
    gcpProjectId: vegadev-499613
    gcpProjectNumber: '566331480334'
    wifServiceAccount: aicoe-sbx-wif-sa-tf@aicoesandox.iam.gserviceaccount.com
    enableStatic: true
    enableNetwork: true
    enableInfra: false
