trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - terraform/projects/aicoe-core/**
      - terraform/modules/**
      - pipelines/**

pool:
  vmImage: ubuntu-latest

extends:
  template: pipeline-template.yml
  parameters:
    projectName: aicoe-core
    tfEnv: dev
    tfProject: aicoe
    gcpProjectId: aicoedev
    gcpProjectNumber: '1034474201742'
    wifServiceAccount: aicoe-sbx-wif-sa-tf@aicoesandox.iam.gserviceaccount.com
    enableStatic: true
    enableNetwork: true
    enableInfra: true
