trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - terraform/projects/omfocuslane/**
      - terraform/modules/**

pool:
  vmImage: ubuntu-latest

extends:
  template: pipeline-template.yml
  parameters:
    projectName: omfocuslane
    tfEnv: dev
    tfProject: om-focus-lane
    gcpProjectId: om-focus-lane
    gcpProjectNumber: '35927785065'
    wifServiceAccount: aicoe-sbx-wif-sa-tf@aicoesandox.iam.gserviceaccount.com
    enableStatic: true
    enableNetwork: true
    enableInfra: true
