trigger:
  branches:
    include:
      - prod
  paths:
    include:
      - terraform/projects/aicoe-core/**
      - terraform/modules/**
      - pipelines/**

pool:
  vmImage: ubuntu-latest

extends:
  template: pipeline-template.yml
  parameters:
    projectName: aicoe-core
    tfEnv: prod
    tfProject: aicoe
    gcpProjectId: aicoeprod
    gcpProjectNumber: '559232860851'
    wifServiceAccount: aicoe-sbx-wif-sa-tf@aicoesandox.iam.gserviceaccount.com
    enableStatic: true
    enableNetwork: true
    enableInfra: true
