trigger:
  branches:
    include:
      - main
      - sandbox-v1
  paths:
    include:
      - terraform/projects/svcmgmtops/**
      - terraform/modules/**

pool:
  vmImage: ubuntu-latest

extends:
  template: pipeline-template.yml
  parameters:
    projectName: svcmgmtops
    tfEnv: sandbox
    tfProject: svcmgmtops
    gcpProjectId: svcmgmtops-sandbox
    gcpProjectNumber: '892497331362'
    wifServiceAccount: aicoe-sbx-wif-sa-tf@aicoesandox.iam.gserviceaccount.com
    enableStatic: true
    enableNetwork: false
    enableInfra: true
