project_name             = "aicoedev"
project                  = "aicoe"
envname                  = "dev"
region                   = "europe-west1"
cloud_run_service_name   = "translation-api-service"
cloud_run_service_name2  = "sales-research-application"
cloud_run_service_name3  = "translation-ui-service"